### ISSUE TITLE
Crash in emv read mode

### ISSUE THREAD

**Issue by vectorialgradha** [doc-rj/smartcard-reader#6] opened 2015-11-04 11:12 UTC
Touching another android device using HCE seems to read some data on the screen but crashes the app with:

```
FATAL EXCEPTION: Thread-2237
Process: org.docrj.smartcard.reader, PID: 30330
java.lang.ExceptionInInitializerError
    at org.docrj.smartcard.emv.GpoApdu.getGpoApdu(GpoApdu.java:40)
    at org.docrj.smartcard.reader.PaymentReaderXcvr.initiateAppProcessing(PaymentReaderXcvr.java:169)
    at org.docrj.smartcard.reader.PaymentReaderXcvr.run(PaymentReaderXcvr.java:87)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: java.lang.NullPointerException: in == null
    at java.util.Properties.load(Properties.java:246)
    at org.docrj.smartcard.emv.EMVTerminal.<clinit>(EMVTerminal.java:67)
    at org.docrj.smartcard.emv.GpoApdu.getGpoApdu(GpoApdu.java:40) 
    at org.docrj.smartcard.reader.PaymentReaderXcvr.initiateAppProcessing(PaymentReaderXcvr.java:169) 
    at org.docrj.smartcard.reader.PaymentReaderXcvr.run(PaymentReaderXcvr.java:87) 
    at java.lang.Thread.run(Thread.java:818) 
```

**Comment by vectorialgradha** [comment] 2015-11-04 11:19
Looks like the error happens only with another android device, using physical plastic cards doesn't crash the emv read mode.

**Comment by doc-rj** [comment] 2015-11-17 21:14
Hi,

I couldn't reproduce this with the two Lollipop phones that I have.  I get this result in emv read mode:

![device-2015-11-17-150957](https://cloud.githubusercontent.com/assets/1207098/11225062/c4202eae-8d3d-11e5-8e0c-fe6d6f4f61a9.png)

Can you provide any details about the devices you're using?

Thanks!

**Comment by doc-rj** [comment] 2015-11-17 21:42
Hi, I haven't been able to reproduce this. Can you provide any details about the two devices and the HCE app running on the second device? Thanks!

**Comment by pickeyboy** [comment] 2016-02-16 23:39
Hey Doc-rj, 

Even I get this error, I compiled and installed the reader app in my Android device. Then select EMV Read and tried to use my NFC enabled bank card and I get exactly the same error. 

Where can I find "terminal.properties" resource? Do I need to prepare this file and copy it somewhere in the mobile device?

**Comment by doc-rj** [comment] 2016-03-29 04:52
pickeyboy, vectorialgradha, please excuse my slowness, I haven't been working on this project recently. Well, I finally got around to fixing this issue in the latest commit: https://github.com/doc-rj/smartcard-reader/commit/53350b24e20a9429e5f5c6e924a1d683bece0025

Let me know if it resolves the issue for you... Some work may be needed yet in Get Processing Options command generation, but at least the crash should be fixed.

**Closed as completed** 2016-03-30 22:16 UTC
